apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: item-mongo
  name: item-mongo
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: mongo:7.0
      name: "7.0"
      referencePolicy:
        type: ""
