version: "3.8"

services:
  item-service:
    build: .
    container_name: item-service
    ports:
      - "8080:8080"    # REST API
      - "50051:50051"  # gRPC
    depends_on:
      - mongo
    environment:
      - PORT=8080
      - GRPC_PORT=50051
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - item-net

  mongo:
    image: mongo:7.0
    container_name: mongo-item
    ports:
      - "27018:27017"
    volumes:
      - item-mongo-data:/data/db
    networks:
      - item-net

volumes:
  item-mongo-data:

networks:
  item-net:
    driver: bridge